version: '3'

services:
  app:
    build:
      context: ./node
    container_name: app
    volumes:
      - ./node:/usr/share/app
    depends_on:
      - mysql
    networks:
      - local

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "8080:8080"
    depends_on:
      - app
    networks:
      - local

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=db_fullcycle
      - MYSQL_USER=admin
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/schema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - local

volumes:
  mysql_data:

networks:
  local:
    driver: bridge
