version: '3'

services:
  mysql:
    image: mysql:8.4.0
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=db_fullcycle
      - MYSQL_USER=admin
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/schema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - local

volumes:
  mysql_data:


networks:
  local:
    driver: bridge
